### ISSUE TITLE
cabal can't find keera-posture package

### ISSUE THREAD

**Issue by marcelopm** [keera-studios/keera-posture#3]
OS: ubuntu 14.10x86_64

I followed the instructions but cabal can't seem to be able to find keera-posture:
```
~/src/keera-posture$ ./installation.sh 
..
Installed keera-hails-0.0.3.3
cabal: There is no package named 'keera-posture'.
You may need to run 'cabal update' to get the latest list of available
packages.
```
Any thoughts?
Cheers

**Comment by ivanperez-keera** [comment]
There may be a problem with the instructions.

Can you please try to git clone this repo to your machine and run the installation script from inside?

**Comment by marcelopm** [comment]
It was cloned,
cheers

**Comment by ivanperez-keera** [comment]
Ok. Keera Posture is now available on hackage. You should be able to:
```
$ cabal sandbox init
$ export PATH=$PWD/.cabal-sandbox/bin:$PATH
$ cabal install alex happy gtk2hs-buildtools # You may not need some of these if you have them.
$ cabal install keera-posture
```
