### ISSUE TITLE
Convert Readme to markdown format

### ISSUE THREAD

**Issue by ivanperez-keera** [keera-studios/keera-posture#8]
Just a few simple steps:
- Rename the readme to README.md
- Update contents of README.md so that headers, sections, code, etc. are rendered appropriately using markdown syntax.
- Modify cabal file so that it points to this new file.

**Comment by cglewis** [comment]
I'll take this one!

**Comment by ivanperez-keera** [comment]
Cool! Thanks :)

**Comment by MineRobber9000** [comment]
I'll take a crack at this one too, if @cglewis doesn't mind.

**Comment by cglewis** [comment]
@MineRobber9000 already submitted a PR for it...
